export const agents = [
  {
    id: 1,
    name: "ContentMaster AI",
    description: "Generate high-quality blog posts, social media content, and marketing copy in seconds.",
    category: "Writing",
    rating: 4.9,
    reviews: 2341,
    price: 29,
    image: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=500&h=500&fit=crop",
    creator: "Alex Chen",
    downloads: 15420,
    tags: ["content", "writing", "seo"],
    features: ["Multi-language support", "SEO optimization", "Brand voice customization"],
  },
  {
    id: 2,
    name: "DataViz Pro",
    description: "Transform raw data into stunning visualizations and interactive dashboards instantly.",
    category: "Data",
    rating: 4.8,
    reviews: 1856,
    price: 39,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=500&fit=crop",
    creator: "Sarah Williams",
    downloads: 12850,
    tags: ["data", "visualization", "analytics"],
    features: ["Real-time updates", "Custom themes", "Export options"],
  },
  {
    id: 3,
    name: "CodeHelper",
    description: "Debug code, suggest improvements, and generate boilerplate with AI-powered assistance.",
    category: "Development",
    rating: 4.7,
    reviews: 3102,
    price: 19,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop",
    creator: "James Developer",
    downloads: 28934,
    tags: ["coding", "debugging", "development"],
    features: ["Multi-language support", "Performance tips", "Test generation"],
  },
  {
    id: 4,
    name: "DesignGenius",
    description: "Create beautiful UI designs, mockups, and brand guidelines powered by AI creativity.",
    category: "Design",
    rating: 4.9,
    reviews: 2567,
    price: 49,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=500&fit=crop",
    creator: "Emma Design",
    downloads: 18765,
    tags: ["design", "ui", "branding"],
    features: ["Component library", "Brand consistency", "Export to Figma"],
  },
  {
    id: 5,
    name: "VoiceGenius",
    description: "Text-to-speech with natural voices, emotion detection, and multi-language support.",
    category: "Audio",
    rating: 4.6,
    reviews: 987,
    price: 24,
    image: "https://images.unsplash.com/photo-1516321318423-f06f70d504f0?w=500&h=500&fit=crop",
    creator: "Michael Audio",
    downloads: 9234,
    tags: ["audio", "speech", "voice"],
    features: ["50+ voices", "Emotion synthesis", "Background music"],
  },
  {
    id: 6,
    name: "MarketAnalyzer",
    description: "Real-time market trends, competitor analysis, and predictive insights for your business.",
    category: "Analytics",
    rating: 4.8,
    reviews: 1456,
    price: 59,
    image: "https://images.unsplash.com/photo-1551836022-4f4b67b1bda0?w=500&h=500&fit=crop",
    creator: "Lisa Business",
    downloads: 7654,
    tags: ["analytics", "market", "business"],
    features: ["Real-time data", "Predictive AI", "Custom reports"],
  },
  {
    id: 7,
    name: "ImageEnhancer",
    description: "Upscale, enhance, and edit photos with AI. Remove backgrounds, apply filters, and more.",
    category: "Image",
    rating: 4.7,
    reviews: 2234,
    price: 14,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=500&fit=crop",
    creator: "David Photo",
    downloads: 34521,
    tags: ["image", "photo", "editing"],
    features: ["4K upscaling", "Batch processing", "Background removal"],
  },
  {
    id: 8,
    name: "EmailCampaign",
    description: "Design, test, and optimize email campaigns with AI-powered copy and A/B testing.",
    category: "Marketing",
    rating: 4.9,
    reviews: 1678,
    price: 34,
    image: "https://images.unsplash.com/photo-1611164850560-ba8b149ea2d5?w=500&h=500&fit=crop",
    creator: "Rachel Marketing",
    downloads: 11234,
    tags: ["email", "marketing", "campaigns"],
    features: ["Template library", "A/B testing", "Analytics"],
  },
];

export const categories = ["All", "Writing", "Data", "Development", "Design", "Audio", "Analytics", "Image", "Marketing"];

export const leaderboard = agents
  .sort((a, b) => b.downloads - a.downloads)
  .slice(0, 10)
  .map((agent, index) => ({
    ...agent,
    rank: index + 1,
  }));
